// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbRC06FikF4u76EtTeaXA_QYm7nhmeTbk',
    appId: '1:321939028016:web:b06590a1d8d4ee21b315f5',
    messagingSenderId: '321939028016',
    projectId: 'bandi-server-db80b',
    authDomain: 'bandi-server-db80b.firebaseapp.com',
    databaseURL: 'https://bandi-server-db80b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bandi-server-db80b.firebasestorage.app',
    measurementId: 'G-06075V6JEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1vDri3ZMQmd1wDAJoVn1pKdvtkWiP0E',
    appId: '1:321939028016:android:b65def261895e741b315f5',
    messagingSenderId: '321939028016',
    projectId: 'bandi-server-db80b',
    databaseURL: 'https://bandi-server-db80b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bandi-server-db80b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu5W2Hff589a4aZYL2rjmXaWU7to9ny1s',
    appId: '1:321939028016:ios:26c1d675eea8ed93b315f5',
    messagingSenderId: '321939028016',
    projectId: 'bandi-server-db80b',
    databaseURL: 'https://bandi-server-db80b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bandi-server-db80b.firebasestorage.app',
    iosBundleId: 'com.example.myHelperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu5W2Hff589a4aZYL2rjmXaWU7to9ny1s',
    appId: '1:321939028016:ios:26c1d675eea8ed93b315f5',
    messagingSenderId: '321939028016',
    projectId: 'bandi-server-db80b',
    databaseURL: 'https://bandi-server-db80b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bandi-server-db80b.firebasestorage.app',
    iosBundleId: 'com.example.myHelperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbRC06FikF4u76EtTeaXA_QYm7nhmeTbk',
    appId: '1:321939028016:web:6a24fcd3a2255d24b315f5',
    messagingSenderId: '321939028016',
    projectId: 'bandi-server-db80b',
    authDomain: 'bandi-server-db80b.firebaseapp.com',
    databaseURL: 'https://bandi-server-db80b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bandi-server-db80b.firebasestorage.app',
    measurementId: 'G-1VMNNYEJ3D',
  );

}