// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlZlKdgw5FtdPAMkLXjl1Hr6GY209X-Zw',
    appId: '1:668922428264:web:0da0afbb448fd7d42074dd',
    messagingSenderId: '668922428264',
    projectId: 'bandi-final',
    authDomain: 'bandi-final.firebaseapp.com',
    databaseURL: 'https://bandi-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bandi-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgLDf7g-r2BeXC9vuIaT2gS57NCO3d-JQ',
    appId: '1:668922428264:android:cd081cf310b5a3512074dd',
    messagingSenderId: '668922428264',
    projectId: 'bandi-final',
    databaseURL: 'https://bandi-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bandi-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHj_9ZzyGo5hTdgFZRcHFm-tigbdD5uLY',
    appId: '1:668922428264:ios:417d540a2f5edacf2074dd',
    messagingSenderId: '668922428264',
    projectId: 'bandi-final',
    databaseURL: 'https://bandi-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bandi-final.firebasestorage.app',
    iosBundleId: 'com.example.myHelperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHj_9ZzyGo5hTdgFZRcHFm-tigbdD5uLY',
    appId: '1:668922428264:ios:417d540a2f5edacf2074dd',
    messagingSenderId: '668922428264',
    projectId: 'bandi-final',
    databaseURL: 'https://bandi-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bandi-final.firebasestorage.app',
    iosBundleId: 'com.example.myHelperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlZlKdgw5FtdPAMkLXjl1Hr6GY209X-Zw',
    appId: '1:668922428264:web:0da0afbb448fd7d42074dd',
    messagingSenderId: '668922428264',
    projectId: 'bandi-final',
    authDomain: 'bandi-final.firebaseapp.com',
    databaseURL: 'https://bandi-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bandi-final.firebasestorage.app',
  );

}